### ISSUE TITLE
有关调试

### ISSUE THREAD

**Issue by lugeilan** [FreezeSoul/OSGi.NET#1]
由于是运行时加载，Bundle在使用vs调试的时候，是命中不了断点的，请问有什么好的调试方法？

**Comment by FreezeSoul** [comment]
#可以修改OSGi.NET.properties文件中的配置项，请在发布时切换回去

#调试模式
OSGi.NET.DEBUG=1

**Comment by lugeilan** [comment]
已成功，谢谢！
